services:
  backend:
    container_name: backend
    image: postgres-explain/backend:latest
    restart: on-failure
    build:
      dockerfile: backend.Dockerfile
      args:
        USER: backend
        GROUP: postgres-explain
      context: backend
    environment:
      CLUSTERS: mycluster,another
      mycluster_CLUSTER_USERNAME: postgres
      mycluster_CLUSTER_HOSTNAME: postgres_one
      mycluster_postgres_CLUSTER_PASSWORD: postgres
      CLICKHOUSE_HOST: clickhouse
      AUTH_TYPE: disabled
      LOG_LEVEL: debug
    ports:
      - "8082:8082"

  postgres_one:
    image: postgres:15
    hostname: postgres_one
    command: -c shared_preload_libraries='pg_stat_statements,auto_explain' -c auto_explain.sample_rate=1 -c auto_explain.log_min_duration=10 -c auto_explain.log_analyze=true -c auto_explain.log_timing=true -c auto_explain.log_buffers=true -c auto_explain.log_verbose=true -c auto_explain.log_triggers=true -c auto_explain.log_settings=true -c auto_explain.log_nested_statements=true -c auto_explain.log_format=JSON
    ports:
      - "5432:5432"
    container_name: postgres_one
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./misc/init.sql:/docker-entrypoint-initdb.d/init.sql

  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "9001:9000"
      - "8123:8123"

  pgbench:
    container_name: pgbench
    image: borealis/pgbench:latest
    build:
      dockerfile: pgbench.Dockerfile
      context: pg_bench
    restart: always # Run continuously
    command: postgres_one
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: postgres